### ISSUE TITLE
Usb undefined

### ISSUE THREAD

**Issue by synnys** [M4ngu/Sweet-Sixteen#1]
I’m flashed my teensy, the sweet sixteen is working fine. But when I connect the usb b port to my computer, my Mac sees it as “undefined” and it’s not receiving any midi. Any idea what this could be? The flashing went fine

**Comment by M4ngu** [comment]
Hi there, did you set the USB as MIDI?
and CPU to 120mhz?
https://www.tesseractmodular.com/manuals/sweet-sixteen-manual#h.p_RE-CxcQ3ERIl
let me know if this helps
Mangu Díaz - Tesseract Modular
https://www.tesseractmodular.com/
https://www.facebook.com/Tesseract-Modular-146727136274298
https://www.modulargrid.net/e/vendors/view/713
https://www.instagram.com/mangudiaz/

**Comment by synnys** [comment]
Yes I did set it as usb midi @ 120mhz

Ruben Hulzebosch

**Comment by synnys** [comment]
do I need to install additional libraries in teensyduino? Because it doesn't error on compile..

![Screenshot 2020-11-06 at 23 14 01](https://user-images.githubusercontent.com/24408246/98419638-c901a700-2085-11eb-9721-116f5efb7de7.png)
these .h includes have a different color though, not sure if that's supposed to be like that?

**Comment by M4ngu** [comment]
to compile it you have to download all files in the folder, not just the
.ino file,
those files included in the folder are the green ones,
the other are libraries,
if it compiles with no errors it's all correct, you don't need to install
any extra library or download any file,

Which firmware are you installing?
my recommendation is the 2.0.1 version modded for SweetSixteen,  because
the settings can be modified with web application,
unless you have the GESS or you need pitch bend, in that case the other
firmwares would be better,
I think there is a compiled version of that, let me know if you can't find
it
all the best
Mangu Díaz - Tesseract Modular
https://www.tesseractmodular.com/
https://www.facebook.com/Tesseract-Modular-146727136274298
https://www.modulargrid.net/e/vendors/view/713
https://www.instagram.com/mangudiaz/

**Comment by synnys** [comment]
I cloned the whole repository so I did have all the files, not just the .ino file.
I uploaded this firmware: https://github.com/M4ngu/Sweet-Sixteen/tree/master/firmware/Sweet_mkII/_16n_faderbank_firmware_Sweet_mkII
(since I have an mk2)
I had no compiler errors and the flashing went fine, I just can't seem to figure out why it's not detected as a USB midi device. It just sees it as undefined... If you have a compiled .hex I could try that would be great

Cheers.

**Comment by synnys** [comment]
Hmm come to think of it, I suddenly have a feeling i know what might have gone wrong...
In the BOM this was the USB connector: https://nl.mouser.com/datasheet/2/670/uj2_bv_1_th-1779281.pdf
However, that was not in stock so I ordered this one in the meantime, while the other in back stock would be delivered: https://nl.mouser.com/ProductDetail/530-SS-52300-002

I just saw that it has a reverse orientation compared to the one in the BOM, so I suspect the pinout is upside down then as well....

**Comment by M4ngu** [comment]
so you have the GESS expander correct?
because if not I'd recommend the 2.0.1 version.

I thought all those USB connectors had the same pinout, anyway I can't see
that info in the specs sheet of one of them :-(
but as you say, the orientation is different, so pins may be also
different, but can't say 100% sure.

To be sure that the USB is working what I do is just to flash the Teensy
using the front USB port, with the module powered, if it flashes ok then
the USB is going fine,
the computer should detect it as a "16n" midi device if everything is
correct.

there you have a compiled HEX from that mkII version,

let me know if it helps

 best
Mangu Díaz - Tesseract Modular
https://www.tesseractmodular.com/
https://www.facebook.com/Tesseract-Modular-146727136274298
https://www.modulargrid.net/e/vendors/view/713
https://www.instagram.com/mangudiaz/

**Comment by synnys** [comment]
installed new USB connector, since i foolishly damaged the original one. (Desoldering was a drama for some reason)
Installed the 2.0.1 firmware, all is workingas it should now and the web-editor is working too.
Case closed!
Thanks for the help.

Ruben
